In [ ]:
import numpy as np

# how to generate a matrix (change entries and number of rows and columns for desired matrices)
M=np.array([
    [1,1,4],
    [0,2,0],
    [1,1,1]
])
print('Matrix M:', M, sep= '\n')

N=np.array([
    [4,0,1],
    [-2,3,5],
    [1,-1,0]
])
print('Matrix N:', N, sep= '\n')

# matrix addition and subtraction
print('Matrix M+N:', M+N, sep= '\n'     )

# matrix multiplication
print('Matrix MN:', M@N, sep= '\n'     )

# calculating determinant and trace
def matrix_properties(matrix):
    determinant = np.linalg.det(matrix)
    trace = np.trace(matrix)
    return determinant, trace

print('Determinant and Trace of M')
det, tr = matrix_properties(M)

print('Determinant:', det)
print('Trace:', tr)

# calcultating eigenvalues and eigenvectors
print(np.linalg.eig(M))

In [13]:
# Question 1

import numpy as np

A=np.array([
    [1,1,4],
    [0,2,0],
    [1,1,1]
])
print('Matrix A:', A, sep= '\n')

print('Matrix A Eigs:', np.linalg.eig(A))

B=np.array([
    [-1,1,0],
    [1,2,1],
    [0,3,-1]
])
print('Matrix B:', B, sep= '\n')

print('Matrix B Eigs:', np.linalg.eig(B))

C=np.array([
    [-1,4,2],
    [4,-1,-2],
    [0,0,6]
])
print('Matrix C:', C, sep= '\n')

print('Matrix C Eigs:', np.linalg.eig(C))

Matrix A:
[[1 1 4]
 [0 2 0]
 [1 1 1]]
Matrix A Eigs: EigResult(eigenvalues=array([ 3., -1.,  2.]), eigenvectors=array([[ 0.89442719, -0.89442719, -0.81110711],
       [ 0.        ,  0.        ,  0.48666426],
       [ 0.4472136 ,  0.4472136 , -0.32444284]]))
Matrix B:
[[-1  1  0]
 [ 1  2  1]
 [ 0  3 -1]]
Matrix B Eigs: EigResult(eigenvalues=array([ 3., -1., -2.]), eigenvectors=array([[-1.96116135e-01,  7.07106781e-01,  3.01511345e-01],
       [-7.84464541e-01, -1.33333472e-16, -3.01511345e-01],
       [-5.88348405e-01, -7.07106781e-01,  9.04534034e-01]]))
Matrix C:
[[-1  4  2]
 [ 4 -1 -2]
 [ 0  0  6]]
Matrix C Eigs: EigResult(eigenvalues=array([ 3., -5.,  6.]), eigenvectors=array([[ 0.70710678, -0.70710678,  0.17609018],
       [ 0.70710678,  0.70710678, -0.17609018],
       [ 0.        ,  0.        ,  0.968496  ]]))


In [42]:
# Question 2 for Matrix A

import numpy as np

VA=np.array([
    [2,-2,5],
    [0,0,-3],
    [1,1,2]
])
print('Eig Vec Matrix V:', VA, sep= '\n')

DA=np.array([
    [3, 0, 0],
    [0, -1, 0],
    [0, 0, 2]
])

print('Eig Val Matrix D:', DA, sep= '\n')

print('V^-1:', np.linalg.inv(VA), sep= '\n')

print('VD(V^-1):', VA@DA@(np.linalg.inv(VA)), sep= '\n')



Eig Vec Matrix V:
[[ 2 -2  5]
 [ 0  0 -3]
 [ 1  1  2]]
Eig Val Matrix D:
[[ 3  0  0]
 [ 0 -1  0]
 [ 0  0  2]]
V^-1:
[[ 0.25        0.75        0.5       ]
 [-0.25       -0.08333333  0.5       ]
 [-0.         -0.33333333 -0.        ]]
VD(V^-1):
[[1. 1. 4.]
 [0. 2. 0.]
 [1. 1. 1.]]


In [36]:
# Question 2 for Matrix B

import numpy as np

VB=np.array([
    [1, -1, 1],
    [4, 0, -1],
    [3, 1,  3]
])
print('Eig Vec Matrix V:', VB, sep= '\n')

DB=np.array([
    [3, 0, 0],
    [0, -1, 0],
    [0, 0, -2]
])

print('Eig Val Matrix D:', DB, sep= '\n')

print('V^-1:', np.linalg.inv(VB), sep= '\n')

print('VD(V^-1):', np.round(VB@DB@(np.linalg.inv(VB))), sep= '\n')

Eig Vec Matrix V:
[[ 1 -1  1]
 [ 4  0 -1]
 [ 3  1  3]]
Eig Val Matrix D:
[[ 3  0  0]
 [ 0 -1  0]
 [ 0  0 -2]]
V^-1:
[[ 0.05  0.2   0.05]
 [-0.75 -0.    0.25]
 [ 0.2  -0.2   0.2 ]]
VD(V^-1):
[[-1.  1.  0.]
 [ 1.  2.  1.]
 [-0.  3. -1.]]


In [17]:
# Question 2 for Matrix C

import numpy as np

VC=np.array([
    [ 1, -1,  2],
    [ 1,  1, -2],
    [ 0,  0,  11]
])
print('Eig Vec Matrix V:', VC, sep= '\n')

DC=np.array([
    [3, 0, 0],
    [0, -5, 0],
    [0, 0, 6]
])

print('Eig Val Matrix D:', DC, sep= '\n')

print('V^-1:', np.linalg.inv(VC), sep= '\n')

print('VD(V^-1):', VC@DC@(np.linalg.inv(VC)), sep= '\n')

Eig Vec Matrix V:
[[ 1 -1  2]
 [ 1  1 -2]
 [ 0  0 11]]
Eig Val Matrix D:
[[ 3  0  0]
 [ 0 -5  0]
 [ 0  0  6]]
V^-1:
[[ 0.5         0.5         0.        ]
 [-0.5         0.5         0.18181818]
 [ 0.          0.          0.09090909]]
VD(V^-1):
[[-1.  4.  2.]
 [ 4. -1. -2.]
 [ 0.  0.  6.]]
